name: ny_times
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  connectivity_plus: ^3.0.6
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  get_it: ^7.5.0
  go_router: ^7.0.0
  http: ^0.13.6
  json_annotation: ^4.8.1
  shared_preferences: ^2.1.0
  url_launcher: ^6.1.11

dev_dependencies:
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.2

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/launcher_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
